### PR TITLE
feat:Localisation

### LINKED ISSUE #81: Localization
Support German

### PR DESCRIPTION
**Pull request by CommanderStorm**
This implements the ability to have multiple languages in this project
This is done as a demo on the bottom Navbar, other parts will follow in follow-up PRs

Resolves #81

# TODO (I need help on these):
- [x] image
- [x] make sure that changing this widget results in the `locale` parameter being changed in `MaterialApp` created by `CampusApp.build()`
       image

### CODE REVIEW

**Comment by CommanderStorm** [comment]
- for the Xcode one, I need someone with Xcode to perform these steps ^^
- For the State management one, I know that other parts of the app (like `useWebView` or the `AuthenticationRouter`) use `ref`. The problem is how do I get `ref` inside `CampusApp.build()`

**Comment by jakobkoerber** [comment]
> * for the Xcode one, I need someone with Xcode to perform these steps ^^

I can do that for you

> * For the State management one, I know that other parts of the app (like `useWebView` or the `AuthenticationRouter`) use `ref`. The problem is how do I get `ref` inside `CampusApp.build()`

Change `class CampusApp extends StatelessWidget` to `class CampusApp extends ConsumerWidget`

**Comment by CommanderStorm** [comment]
Okay, I have added a draft of persistent settings, but I think I am still missing a part.
The other state-management mechanisms means that this would not be a setting, but rather a temporary toggle.

What do you think? How would you do this?

**Comment by jakobkoerber** [comment]
> What do you think?
> 
> How would you implement this?

Persistent settings are already implemented and will be merged with the places+search feature. Therefore I would stick to that implementation :)

**Comment by jakobkoerber** [comment]
> Previously existing state-management mechanisms would mean that this would not be a setting, but rather a temporary toggle.

What exactly do you mean?

**Comment by CommanderStorm** [comment]
> > Previously existing state-management mechanisms would mean that this would not be a setting, but rather a temporary toggle.
> 
> What exactly do you mean?

`StateProvider<Locale>` is not persistent between app-restarts

**Comment by jakobkoerber** [comment]
> Should I rebase this PR onto said branch or should we leave this open until then?

I will merge them together once the branch I'm working on is ready to get merged

**Review by jakobkoerber — APPROVED** [review]

**Pull request merged**
